--Q1.
SELECT * FROM EMP
WHERE ENAME LIKE '%S';

--Q2.
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 30
AND   JOB = 'SALESMAN';

--Q3.
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE SAL > 2000
AND   DEPTNO IN (20, 30);

SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE SAL > 2000
AND   DEPTNO  = 20
UNION
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE SAL > 2000
AND   DEPTNO  = 30;

--Q4.
SELECT * FROM EMP
WHERE SAL < 2000
OR   SAL > 3000;

--Q5.
SELECT ENAME, EMPNO, SAL, DEPTNO
FROM EMP
WHERE ENAME LIKE '%E%'
AND   DEPTNO = 30
AND SAL NOT BETWEEN 1000 AND 2000;

--Q6.
SELECT * FROM EMP
WHERE MGR IS NOT NULL
AND COMM IS NULL
AND JOB IN ('MANAGER', 'CLERK')
AND ENAME NOT LIKE '_L%';