SELECT E.JOB, E.EMPNO, E.ENAME, E.SAL, E.DEPTNO, D.DNAME
  FROM EMP E, DEPT D
 WHERE E.DEPTNO = D.DEPTNO
   AND JOB = (SELECT JOB
                FROM EMP
               WHERE ENAME = 'ALLEN');

2번 다시 풀기

SELECT E.EMPNO, E.ENAME, E.JOB, E.DEPTNO, D.DNAME, D.LOC
 FROM EMP E, DEPT D
WHERE D.DEPTNO = E.DEPTNO
 AND E.DEPTNO = 10
 AND WHERE E.JOB NOT IN (SELECT JOB
                        FROM EMP
                        WHERE DEPTNO = 30);